version: '2'
services:

  zoo1:
    image: zookeeper:3.4.9
    hostname: zoo1
    ports:
      - "2181:2181"
    environment:
        ZOO_MY_ID: 1
        ZOO_PORT: 2181
        ZOO_SERVERS: server.1=zoo1:2888:3888
    #volumes: # uncomment to see kafka data directory
    #  - ./confluent/zoo1/data:/data
    #  - ./confluent/zoo1/datalog:/datalog
    networks:
      - elk

  kafka1:
    image: confluentinc/cp-kafka:5.1.2
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #volumes: # uncomment to see kafka data directory
    #  - ./confluent/kafka1/data:/var/lib/kafka/data
    networks:
      - elk
    depends_on:
      - zoo1
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
    volumes:
     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: youpassword
    networks:
     - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.4.0
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: youpassword
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:6.4.0
    links:
    - elasticsearch
    volumes: ## default directories https://www.elastic.co/guide/en/logstash/current/dir-layout.html#docker-layout
    - ./logstash/patterns/:/usr/share/logstash/patterns/
    - ./logstash/conf.d/:/usr/share/logstash/pipeline/ 
    - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    networks:
      - elk
    depends_on:
    - elasticsearch
    - kafka1

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.4.0
    command: filebeat -e -strict.perms=false
    #volumnes mount depend on you OS ( Windows or Linux )
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./filebeat/logs_scanned_directory:/usr/share/filebeat/logs
    networks:
      - elk
    links:
      - kafka1
      - kibana
  
  #apm-server:
  #  image: "docker.elastic.co/apm/apm-server:6.4.0"
  #  volumes: 
  #    - ./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml"
  #  ports:
  #    - "8200:8200"
  #  links:
  #    - elasticsearch

  
      
networks:
  elk:
    driver: bridge
